# Generated by Django 3.0.1 on 2020-03-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('seller_id', models.PositiveIntegerField(help_text='Identificador unico del vendedor en la API de mercadolibre', primary_key=True, serialize=False)),
                ('trm', models.FloatField(help_text='Conversion de la moneda del proveedor a 1 USD.')),
                ('shipping_vzla', models.FloatField(help_text='Costo MAXIMO de envio dentro de venezuela(en USD).')),
                ('meli_tax', models.FloatField(help_text='PORCENTAJE de la comision de mercadolibre.')),
                ('utility', models.IntegerField(help_text='PORCENTAJE de la utilidad de los socios.')),
                ('usd_variation', models.FloatField(default=0, help_text='Precio de actualizacion del USD por encima de la taza.')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.PositiveIntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meli', models.PositiveIntegerField(help_text='Identificador unico de la categoria en mercadolibre sin el prefijo MLV,MCO,MCL,etc', null=True, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('bad_category', models.BooleanField(default=False)),
                ('leaf', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parent', to='store.Category')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_root', to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('reference', models.BigIntegerField(default=None, null=True, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('cost_price', models.FloatField(null=True)),
                ('ship_price', models.FloatField(null=True)),
                ('provider_sku', models.CharField(max_length=50, unique=True)),
                ('provider_link', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, null=True)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('last_update', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('modifiable', models.BooleanField(default=True)),
                ('height', models.FloatField(default=None, null=True)),
                ('width', models.FloatField(default=None, null=True)),
                ('length', models.FloatField(default=None, null=True)),
                ('weight', models.FloatField(default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('nickname', models.CharField(max_length=60, null=True, unique=True)),
                ('id', models.PositiveIntegerField(help_text='Identificador unico del vendedor en la WEB/API del proveeedor', primary_key=True, serialize=False)),
                ('bad_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductForStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pausada'), (1, 'Activa'), (2, 'Cerrada'), (3, 'Inactiva'), (4, 'Bajo revision'), (5, 'Pago Requerido')], default=0)),
                ('no_problem', models.BooleanField(default=False)),
                ('sku', models.CharField(default=None, max_length=20, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BusinessModel')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, 'Cancelada'), (0, 'Ofertado en MercadoLibre'), (1, 'Pagado'), (2, 'Procesando'), (3, 'Recibido en Bodega'), (4, 'Salida internacional'), (5, 'Recibido en Tienda'), (6, 'Completado')], default=0)),
                ('store_order_id', models.BigIntegerField(unique=True)),
                ('provider_order_id', models.BigIntegerField(null=True, unique=True)),
                ('date_offer', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('quantity', models.IntegerField()),
                ('destination_place', models.CharField(default='Venezuela', max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Buyer')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipping')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='pay',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Pay'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(choices=[(-1, 'Negativo.'), (0, 'Neutral.'), (1, 'Positivo.')])),
                ('reason', models.IntegerField(choices=[(0, 'Me quede sin stock.'), (1, 'No pude contactar al comprador.'), (2, 'El Comprador no tenia suficiente dinero.'), (3, 'El comprador decidio no comprar.')], null=True)),
                ('fulfilled', models.BooleanField()),
                ('message', models.CharField(max_length=159)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meli', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=350)),
                ('value_id', models.CharField(max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
