# Generated by Django 3.0.1 on 2020-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
