# Generated by Django 3.0.1 on 2020-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productforstore',
            name='sku',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
