# Generated by Django 3.0.1 on 2020-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200116_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ofertado en MercadoLibre'), (1, 'Pagado'), (2, 'Procesando'), (3, 'Recibido en Bodega'), (4, 'Salida internacional'), (5, 'Recibido en Tienda'), (6, 'Completado')], default=0),
        ),
    ]
