# Generated by Django 3.0.1 on 2020-03-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200311_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='shipping_vzla',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='country',
            field=models.CharField(default='ve', help_text='Abreviatura del pais online. Ej: ve, co, do, mx', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='name',
            field=models.CharField(default='go_shop', help_text='Nombre de la tienda. Max 10 caracteres', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='shipping',
            field=models.FloatField(default=10, help_text='Costo MAXIMO de envio dentro del pais es decir la ultima milla(en USD).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productforstore',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AddField(
            model_name='productforstore',
            name='sale_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productforstore',
            name='sku',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
