# Generated by Django 3.0.1 on 2020-01-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200118_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='nickname',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
