# Generated by Django 3.0.1 on 2020-03-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200316_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productforstore',
            old_name='seller',
            new_name='store',
        ),
    ]
