# Generated by Django 3.0.1 on 2020-01-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200126_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='father',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
