# Generated by Django 3.0.1 on 2020-01-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200127_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
