# Generated by Django 3.0.1 on 2020-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200127_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider_sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
