# Generated by Django 3.0.1 on 2020-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200128_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
