# Generated by Django 3.0.1 on 2020-01-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200128_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.CharField(max_length=255),
        ),
    ]
