# Generated by Django 3.0.1 on 2020-01-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200128_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
