# Generated by Django 3.0.1 on 2020-01-30 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200129_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
