# Generated by Django 3.0.1 on 2020-01-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200131_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifiable',
            field=models.BooleanField(default=True),
        ),
    ]
