# Generated by Django 3.0.1 on 2020-02-01 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_product_modifiable'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_place',
            field=models.CharField(default='Caracas Chacaito', max_length=255),
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='new',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order'),
        ),
        migrations.AddField(
            model_name='new',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
