# Generated by Django 3.0.1 on 2020-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200202_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pausada'), (1, 'Activa'), (2, 'Cerrada'), (3, 'Inactiva'), (4, 'Bajo revision'), (5, 'Pago Requerido')], default=0),
        ),
    ]
