# Generated by Django 3.0.1 on 2020-02-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_problem',
            field=models.BooleanField(default=False),
        ),
    ]
