# Generated by Django 3.0.1 on 2020-02-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_place',
            field=models.CharField(default='Venezuela', max_length=255),
        ),
    ]
