# Generated by Django 3.0.1 on 2020-02-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_no_problem'),
        ('store', '0027_auto_20200204_1143'),
    ]

    operations = [
    ]
