# Generated by Django 3.0.1 on 2020-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_merge_20200207_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_place',
            field=models.CharField(default='Caracas Chacaito', max_length=255),
        ),
        migrations.AlterField(
            model_name='pay',
            name='reference',
            field=models.BigIntegerField(default=None, null=True, unique=True),
        ),
    ]
