# Generated by Django 3.0.1 on 2020-02-09 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200208_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='father',
        ),
        migrations.AddField(
            model_name='category',
            name='bad_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='leaf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parent', to='store.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_root', to='store.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(help_text='Identificador unico de la categoria en mercadolibre sin el prefijo MLV,MCO,MCL,etc', primary_key=True, serialize=False),
        ),
    ]
