# Generated by Django 3.0.1 on 2019-12-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mco', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('available_quantify', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meli.Provider')),
            ],
        ),
    ]
