# Generated by Django 3.0.1 on 2020-01-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_sdk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='app_id',
        ),
        migrations.AddField(
            model_name='token',
            name='seller_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
