# Generated by Django 3.0.1 on 2020-01-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Enviado'), (1, 'Recibido en oficinas'), (2, 'Completado')], default=0)),
                ('date_send', models.DateTimeField()),
                ('date_completed', models.DateTimeField(null=True)),
                ('amount', models.FloatField(default=0)),
                ('guide', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=250)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.Shipper')),
            ],
        ),
    ]
