# Generated by Django 3.0.1 on 2020-03-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200311_1826'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperInternational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInternational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('zipcode', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShipperInternational')),
            ],
        ),
    ]
