# Generated by Django 3.0.1 on 2020-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='guide',
            field=models.BigIntegerField(),
        ),
    ]
